spring.application.name=CityCare
server.port=9090
server.servlet.context-path=/api

# Database
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3306/Citycare
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate ddl-auto (keeps the same logic as your MySQL setup)
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/citycare
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Recommended: Explicitly set the PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jackson.serialization.fail-on-empty-beans=false

# JWT
#app.jwt.secret=CityCareSecretKey2024VeryLongAndSecureKeyForHMACAlgorithmMinimum256Bits
#app.jwt.expiration-ms=86400000

# Springdoc (Swagger)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
